import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: { flex: 1 },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  topZone: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "33%",
    zIndex: 2,
  },
  kiteImage: { position: "absolute", width: 42, height: 42 },
  container: { flex: 1, justifyContent: "flex-end" },
  content: { paddingHorizontal: 24, paddingBottom: 48 },
  header: { alignItems: "center", marginBottom: 48 },
  title: {
    fontSize: 42,
    fontWeight: "bold",
    color: "#B3D9F2",
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  subtitle: {
    fontSize: 16,
    color: "#fff",
    textAlign: "center",
    marginTop: 8,
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  authContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 16,
    padding: 24,
  },
  button: {
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  googleButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  googleButtonText: { color: "#000", fontSize: 16, fontWeight: "600" },
  devButton: { backgroundColor: "#FF6B35" },
  devButtonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  divider: { flexDirection: "row", alignItems: "center", marginVertical: 24 },
  dividerLine: { flex: 1, height: 1, backgroundColor: "#ddd" },
  dividerText: { marginHorizontal: 12, color: "#666", fontSize: 14 },
  emailContainer: { gap: 12 },
  input: {
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  emailButton: { backgroundColor: "#007AFF" },
  emailButtonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  verifyTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#000",
    textAlign: "center",
    marginBottom: 12,
  },
  verifySubtitle: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
    marginBottom: 8,
  },
  verifyEmail: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
    textAlign: "center",
    marginBottom: 24,
  },
  verifyInstructions: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginBottom: 12,
  },
  countdown: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#007AFF",
    textAlign: "center",
    marginVertical: 24,
    fontVariant: ["tabular-nums"],
  },
  codeInput: {
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 32,
    fontWeight: "bold",
    letterSpacing: 8,
    textAlign: "center",
    borderWidth: 2,
    borderColor: "#007AFF",
    marginBottom: 16,
    fontVariant: ["tabular-nums"],
  },
  resendButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#007AFF",
    marginBottom: 12,
  },
  resendButtonText: { color: "#007AFF", fontSize: 16, fontWeight: "600" },
  cancelButton: { backgroundColor: "#fff" },
  cancelButtonText: { color: "#666", fontSize: 16, fontWeight: "600" },
  disclaimerContainer: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
  },
  disclaimerText: {
    fontSize: 13,
    color: "#666",
    textAlign: "center",
    lineHeight: 18,
  },
  disclaimerLink: { color: "#007AFF", fontWeight: "600" },
});
