import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  stepContainer: { gap: 20 },
  title: { fontSize: 24, fontWeight: "bold", color: "#000", marginBottom: 8 },
  subtitle: { fontSize: 14, color: "#666", marginBottom: 12 },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: "#000",
    backgroundColor: "#fff",
  },
  currentEmail: {
    backgroundColor: "#f5f5f5",
    padding: 12,
    borderRadius: 8,
    gap: 4,
  },
  currentEmailLabel: { fontSize: 12, color: "#666" },
  currentEmailValue: { fontSize: 16, color: "#000", fontWeight: "500" },
  emailDropdown: {
    backgroundColor: "#f9f9f9",
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    gap: 6,
  },
  emailDropdownLabel: { fontSize: 12, color: "#999", fontWeight: "500" },
  emailDropdownValue: { fontSize: 16, color: "#007AFF", fontWeight: "600" },
  linkButton: { padding: 8 },
  linkButtonText: {
    color: "#007AFF",
    fontSize: 14,
    textDecorationLine: "underline",
  },
  button: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  primaryButton: { backgroundColor: "#007AFF" },
  secondaryButton: {
    borderWidth: 1,
    borderColor: "#007AFF",
    backgroundColor: "transparent",
  },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  secondaryButtonText: { color: "#007AFF", fontSize: 16, fontWeight: "600" },
  buttonDisabled: { opacity: 0.6 },
  buttonGroup: { gap: 12, marginTop: 8 },
  timerText: {
    fontSize: 14,
    color: "#FF6B6B",
    fontWeight: "600",
    textAlign: "center",
    paddingVertical: 8,
  },
});
