import { StyleSheet, Platform, ViewStyle } from "react-native";

// Cross-platform shadow
const cardShadow: ViewStyle = Platform.select({
  ios: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  android: { elevation: 2 },
  default: {},
}) as ViewStyle;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F9F9F9" },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9F9F9",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  title: { fontSize: 20, fontWeight: "bold", color: "#000" },
  closeButton: { paddingVertical: 8, paddingHorizontal: 12 },
  closeButtonText: { color: "#007AFF", fontSize: 16, fontWeight: "600" },
  valueInfo: {
    backgroundColor: "#E8F5E9",
    padding: 16,
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 12,
  },
  valueLabel: {
    fontSize: 12,
    color: "#2E7D32",
    fontWeight: "600",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  valueStatement: { fontSize: 15, lineHeight: 22, color: "#1B5E20" },
  content: { flex: 1, paddingHorizontal: 20 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
    marginTop: 24,
    marginBottom: 16,
  },
  emptyState: { alignItems: "center", paddingVertical: 40 },
  emptyText: { fontSize: 16, color: "#666", marginBottom: 8 },
  emptySubText: { fontSize: 14, color: "#999", textAlign: "center" },
  priorityCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    ...cardShadow,
  },
  priorityCardChanged: { borderWidth: 2, borderColor: "#4CAF50" },
  priorityInfo: { flex: 1, marginRight: 16 },
  priorityHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  priorityTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
    marginRight: 8,
  },
  anchoredBadge: {
    fontSize: 11,
    color: "#2196F3",
    backgroundColor: "#E3F2FD",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    fontWeight: "600",
    overflow: "hidden",
  },
  priorityDescription: { fontSize: 14, color: "#666", lineHeight: 20 },
  footer: {
    padding: 20,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  saveButton: {
    backgroundColor: "#4CAF50",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  saveButtonDisabled: { backgroundColor: "#C8E6C9" },
  saveButtonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
});
