import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  title: { fontSize: 20, fontWeight: "bold", color: "#000" },
  cancelButton: { paddingVertical: 8, paddingHorizontal: 12 },
  cancelText: { color: "#007AFF", fontSize: 16, fontWeight: "600" },
  content: { flex: 1 },
  scrollContent: { padding: 20 },
  infoBox: {
    backgroundColor: "#E8F5E9",
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  infoText: { fontSize: 14, lineHeight: 20, color: "#1B5E20" },
  totalBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F5F7FA",
    padding: 16,
    borderRadius: 12,
    marginBottom: 24,
  },
  totalLabel: { fontSize: 18, fontWeight: "600", color: "#000" },
  totalValue: { fontSize: 24, fontWeight: "bold", color: "#4CAF50" },
  totalValueError: { color: "#F44336" },
  weightItem: { marginBottom: 24 },
  statementText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#000",
    marginBottom: 12,
  },
  sliderContainer: { flexDirection: "row", alignItems: "center", height: 50 },
  slider: { flex: 1, height: 40 },
  weightValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4CAF50",
    width: 70,
    textAlign: "right",
    minHeight: 20,
  },
  weightValueZero: { color: "#D32F2F" },
  warningBox: {
    backgroundColor: "#FFEBEE",
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    marginTop: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#D32F2F",
  },
  warningText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#B71C1C",
    fontWeight: "500",
  },
  resetButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#007AFF",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 8,
  },
  resetButtonText: { color: "#007AFF", fontSize: 16, fontWeight: "600" },
  footer: {
    padding: 20,
    paddingBottom: 34,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  saveButton: {
    backgroundColor: "#4CAF50",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  saveButtonDisabled: { backgroundColor: "#C8E6C9" },
  saveButtonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
});
